### ISSUE TITLE
Exclude Netlify and Vercel bots

### ISSUE THREAD

**Issue by MaybeThisIsRu** [plausible/analytics#280]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
I host a static site on [Vercel](https://vercel.com/). After each deploy, I immediately and usually see a new visitor.

I *suspect* this could be a Vercel bot and would request a review and exclusion from analytics traffic if necessary.

The visit is always from the USA, which is what drew my suspicion. It's detected by Plausible as a Windows Laptop using Chrome.

**Comment by mr-islam** [comment]
I think I get something similar on Netlify—a "headless chrome" browser agent. 

What would a solution be to unintended "visitors" like this?

**Comment by ukutaht** [comment]
If Vercel and Netlify bots identify themselves via `User-Agent`, we could add them to this list: https://github.com/matomo-org/device-detector/blob/master/regexes/bots.yml

Plausible uses this list to filter out bots based on the user-agent.

**Comment by hirusi** [comment]
Filed a help request here: https://github.com/vercel/vercel/discussions/5095

**Comment by orenyomtov** [comment]
I am also getting "Headless Chrome" browser hits when deploying to Netlify.
Would be great if they can be ignored.

**Comment by hirusi** [comment]
Vercel have created a `User-Agent` of something like `Vercelbot (+https://vercel.com)`. Does that help take it forward?

**Comment by metmarkosaric** [comment]
Thanks @hirusi! I've submitted an issue [here](https://github.com/matomo-org/device-detector/issues/6361). Let's see if that's enough info for Vercel bot to be added to the bot list.

And about Netlify @orenyomtov @mr-islam: would be great if they could identify themselves as a bot in their user-agent too like Vercel just did. Thanks!

**Comment by mr-islam** [comment]
Just [submitted a request](https://community.netlify.com/t/user-agent-for-netlify-bots/21577) for the `user-agent` on Netlify's forum 👌️

**Comment by hirusi** [comment]
I am no longer seeing Vercel's bots in Plausible. Could it be that the word "bot" appearing in the `User-Agent` is enough for the source filters to block it? I can see that [the request is still open](https://github.com/matomo-org/device-detector/issues/6361).

**Comment by hirusi** [comment]
It might be enough:

https://github.com/matomo-org/device-detector/blob/master/regexes/bots.yml#L2058

**Comment by mr-islam** [comment]
Netlify support said they will not change the current `user-agent` to preserve compatibility for users who use the current one which includes `HeadlessChrome`.

Not sure how to proceed from here, maybe the Matomo filters should just look out for anything with the string `headless` as well

**Comment by tckb** [comment]
@mr-islam  is the user-agent from netlify is `Vercelbot (+https://vercel.com)` ?

**Comment by mr-islam** [comment]
@tckb They informed me that the user-agent from Netlify includes the identifiable string "HeadlessChrome", as per the Netlify forum post mentioned before

`Vercelbot (+https://vercel.com)` is the user-agent for Vercel bots

**Comment by metmarkosaric** [comment]
We're no longer counting HeadlessChrome so this should no longer be an issue.

**Comment by dominikmayer** [comment]
I still get a visit shown every time my Netlify site deploys. Device is a tablet with Chrome running on Linux.

**Comment by niklaas** [comment]
> I still get a visit shown every time my Netlify site deploys. Device is a tablet with Chrome running on Linux.

I can confirm this.

**Comment by metmarkosaric** [comment]
hmm thanks for reporting! Netlify must have changed something as according to the linked post above they were using HeadlessChrome which we no longer count (https://answers.netlify.com/t/user-agent-for-netlify-bots/21577)

**Comment by vesvalim** [comment]
> hmm thanks for reporting! Netlify must have changed something as according to the linked post above they were using HeadlessChrome which we no longer count (https://answers.netlify.com/t/user-agent-for-netlify-bots/21577)

It is still a problem with Netlify. I see a Netlify bot (Chrome 86.0 and GNU/Linux) after every deploy.

**Comment by kasbah** [comment]
I just spotted them too on a new site I set up with Plausible (i.e. getting no visitors aside from me and the Netlify bot).

**Comment by waylonrobert** [comment]
This is still a problem with Netlify. I do a build once per day and it always shows up (my highest analytics hit is from the Linux OS)

**Comment by hirusi** [comment]
If any one of you have access to the site access log, could you please share the user agent in full? :)

**Comment by ukutaht** [comment]
> If any one of you have access to your site access logs, could you please share the user agent in full? :)

That would be really helpful

**Comment by waylonrobert** [comment]
As far as I know, Netlify doesn't give you access logs.

**Comment by Totalus** [comment]
> As far as I know, Netlify doesn't give you access logs.


Yet with a bit of imagination you can get the answer delivered right into your Plausible dashboard:

```js
window.onload = function() {
    plausible("Headers", {props: {UserAgent: navigator.userAgent}});      
}
```

UserAgent: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.0 Safari/537.36`

**Comment by waylonrobert** [comment]
@Totalus Forgive me, I'm not sure how this helps this issue. I can't inject this into whatever process occurs that results in the Netlify build hit (I'm thinking it's the one that checks to make sure the site works and grabs a screenshot).

**Comment by Totalus** [comment]
> @Totalus Forgive me, I'm not sure how this helps this issue. I can't inject this into whatever process occurs that results in the Netlify build hit (I'm thinking it's the one that checks to make sure the site works and grabs a screenshot).

Forget about the script. The script is just the hack I used to get the hands on Netlify's full `user-agent` header. I posted it for your curiosity.

The real useful info is the actual header, since we were trying to get the hands on it to properly filter the Netlify requests out of the analytics.

>>    If any one of you have access to your site access logs, could you please share the user agent in full? :)
>
>That would be really helpful

Now we have it : `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.0 Safari/537.36`

**Comment by waylonrobert** [comment]
> > @Totalus Forgive me, I'm not sure how this helps this issue. I can't inject this into whatever process occurs that results in the Netlify build hit (I'm thinking it's the one that checks to make sure the site works and grabs a screenshot).
> 
> Forget about the script. The script is just the hack I used to get the hands on Netlify's full `user-agent` header. I posted it for your curiosity.

Thanks!

> The real useful info is the actual header, since we were trying to get the hands on it to properly filter the Netlify requests out of the analytics.

D'oh! Should have realized, my apologies. 

> > > If any one of you have access to your site access logs, could you please share the user agent in full? :)
> > 
> > 
> > That would be really helpful
> 
> Now we have it : `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.0 Safari/537.36`

🙌🏻

**Comment by ukutaht** [comment]
Thanks @Totalus. I tested and this is parsed in Plausible as follows

```
Browser: Chrome
Browser Version: 86.0
Operating System: GNU/Linux
Operating System version: --
```

Confirms what @vesvalim said.

Unfortunately the UA string does not contain anything specific to Netlify. Excluding just this string would potentially exclude legitimate visitors (see https://plausible.io/plausible.io?browser=Chrome&browser_version=86.0&os=GNU%2FLinux).

Any suggestons on how to exclude these bots?

In the past I've thought about getting a list of known datacenter IP addresses so we can exclude pageviews triggered from data centers / server farms. That would potentially catch cases like this.

**Comment by Totalus** [comment]
I'm pretty sure I can also get the http headers and the IP address of the Netlify request, then we'll see if there is anything we can use to filter the request.

**Comment by ukutaht** [comment]
Thanks a lot @Totalus 

According to ip2proxy this is coming from an AWS datacenter in Virginia. 

![Screenshot from 2021-08-24 10-12-23@2x](https://user-images.githubusercontent.com/3731516/130573146-50d43b0f-6b58-49fa-ac87-dff4b88e6938.png)

It should be possible to buy a list like this and automatically exclude hits from known datacenter IP addresses.

**Comment by Totalus** [comment]
There seem to be [public ASN databases](https://iptoasn.com/). You can search for `14618` to find all ip ranges related to this specific ASN, and more.

**Comment by mmasouras** [comment]
Hi, I am concerned Plausible might be counting Headless Chrome requests as valid requests. Since I don't have visibility into the most popular User Agents in the dashboard, I can't be sure. Looking at the file mentioned above:
https://github.com/matomo-org/device-detector/blob/master/regexes/bots.yml
I can't see any references to "Headless". 

Here is a user-agent that is very frequent in our access logs:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/79.0.3945.0 Safari/537.36

**Comment by metmarkosaric** [comment]
hi @mmasouras! we exclude all Headless Chrome by default. it's something we added in addition to the device-detector list.

**Comment by metmarkosaric** [comment]
[one report from twitter](https://twitter.com/Design__Pattern/status/1485675173789405186/photo/1) that fits here:

"does this look like potential 🤖 behavior? In the last 30 days someone from Santa Clara, California has hit my website 90+ times. The odd thing here is @nextjs doesn’t expose /[slug] so them hitting that 30 times seems weird…"

**Comment by metmarkosaric** [comment]
anyone still experiencing this? vercel bot is [blocked directly by the blocklist we use](https://github.com/matomo-org/device-detector/search?q=vercel), headlesschrome is excluded by us in addition to the blocklist which should take care of netlify.

**Comment by metmarkosaric** [comment]
closing this as it is fixed but please do share if you see any more issues with vercel or netlify

**Comment by grssnbchr** [comment]
Hey, I am still seeing this. After every deployment on Vercel, we get a couple of requests originating from the USA. 
They come from various user agents apparently, but never interact with the site (no goals triggered), no other pages viewed than the entry page.

Are these not supposed to be blocked in a way?


![image](https://github.com/user-attachments/assets/60b886b1-4d21-4a48-9068-821fb7ec84f6)

**Comment by colinwilson** [comment]
Seeing the same with Vercel deployments. As far as I can tell, it's Vercel's deployment screenshot service that's triggering these views. Looks like the (new?) User Agent is `vercel-screenshot/1.0`

![Image](https://github.com/user-attachments/assets/900b0aa0-76cd-41bf-8a5f-e0ede2232aff)

**EDIT**: You can resolve my specific issue a couple of ways...
1. Add a `robots.txt` file to your app's `/app` directory to disallow the `vercel-screenshot/1.0` user-agent (but allow all others):
```
User-agent: vercel-screenshot/1.0
Disallow: /

User-agent: *
Disallow:
```
2. Or, since Vercel's deployment screenshot is performed on a generated 'preview' domain, you can configure plausible to [allow traffic only from your production domain/sub-domain](https://plausible.io/docs/subdomain-hostname-filter#allow-traffic-from-specific-hostnames-only)
